"""make task goal_id nullable

Revision ID: 179a9af82a91
Revises: a1b2c3d4e5f6
Create Date: 2026-04-26 22:31:56.349723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179a9af82a91'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('weekly_hours_target', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_budgets_id'), 'category_budgets', ['id'], unique=False)
    op.create_table('daily_conclusions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_conclusions_date'), 'daily_conclusions', ['date'], unique=False)
    op.create_index(op.f('ix_daily_conclusions_id'), 'daily_conclusions', ['id'], unique=False)
    op.create_index(op.f('ix_dictionary_words_id'), 'dictionary_words', ['id'], unique=False)
    op.create_index(op.f('ix_practice_sessions_id'), 'practice_sessions', ['id'], unique=False)
    op.alter_column('tasks', 'goal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('time_blocks', sa.Column('notified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_blocks', 'notified_at')
    op.alter_column('tasks', 'goal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_practice_sessions_id'), table_name='practice_sessions')
    op.drop_index(op.f('ix_dictionary_words_id'), table_name='dictionary_words')
    op.drop_index(op.f('ix_daily_conclusions_id'), table_name='daily_conclusions')
    op.drop_index(op.f('ix_daily_conclusions_date'), table_name='daily_conclusions')
    op.drop_table('daily_conclusions')
    op.drop_index(op.f('ix_category_budgets_id'), table_name='category_budgets')
    op.drop_table('category_budgets')
    # ### end Alembic commands ###
