"""add_telegram_chat_id_to_person

Revision ID: 9b7a4a2b1c16
Revises: d1edd21428b6
Create Date: 2026-04-14 22:10:52.363281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b7a4a2b1c16'
down_revision: Union[str, Sequence[str], None] = 'd1edd21428b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('telegram_chat_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'telegram_chat_id')
    # ### end Alembic commands ###
